def inverte(frase):
    frase= frase.lower()
    x= frase.replace('.',' ')
    x= x.replace('?','.')
    x= x.replace(',',' ') 
    x= x.replace('-',' ')
    x= x.replace('!',' ')
    x= x.split()
    x= tuple(x)
    return x.join(' ')