def inverte (frase):
    frase = frase.replace(",", " ")
    frase = frase.replace(".", " ")
    frase = frase.replace("-", " ")
    frase = frase.replace("!", " ")
    frase = frase.replace("?", " ")
    frase = frase.replace(":", " ")
    frase = frase.replace(";", " ")
    frase = frase.lower()
    separa = frase.split()
    separa.reverse()
    return " ".join(separa)