def inverte(frase):
    s=frase.replace(',',' ')
    s1=s.replace('.',' ')
    s2=s1.replace(';',' ')
    s3=s2.replace(':',' ')
    s4=s3.replace('?', ' ')
    s5=s4.replace('!',' ')
    s6=s5.replace('...',' ')
    s7=str.lower(s5)
    str.split(s7)
    list.reverse(st)r.split(s7))
    return list.reverse(st)r.split(s7))