def inverte(frase):
    frase = frase.lower()
    frase = frase.split('-')
    frase = ' '.join(frase)
    frase = frase.split(',')
    frase = ' '.join(frase)
    frase = frase.split(':')
    frase = ' '.join(frase)
    frase = frase.split(';')
    frase = ' '.join(frase)
    frase = frase.split('.')
    frase = ' '.join(frase)
    frase = frase.split('?')
    frase = ' '.join(frase)
    frase = frase.split('!')
    frase = ' '.join(frase)
    frase = frase.split()
    frase = ' '.join(frase[::-1])
    return frase