aa=str.replace(x,'!',' ')
    aa=str.replace(aa,'.',' ')
    aa=str.replace(aa,',',' ')
    aa=str.replace(aa,':',' ')
    aa=str.replace(aa,';',' ')
    aa=str.replace(aa,'-',' ')
    aa=str.replace(aa,'?',' ')