def inverte (frase):
    frase=frase.replace('.',' ')
    frase=frase.replace('?',' ')
    frase=frase.replace(',',' ')
    frase=frase.replace('!',' ')
    frase=frase.replace('-',' ')
    frase=str.lower(frase)
    palavras=frase.split( )
    palavras.reverse( )
    return ' '.join(palavras)