def inverte(s):
    modfpoint = str.replace(s,'...','.')
    fpoint = str.replace(modfpoint,'.','')
    reexcl = str.replace(fpoint,'!','')
    reint = str.replace(reexcl,'?','')
    reevirg = str.replace(reint,',','')
    repointvirg = str.replace(reevirg,';','')
    redoisp = str.replace(repointvirg,':','')
    retr = str.replace(redoisp,'-','')
    reasp = str.replace(retr,'"','')
    repar1 = str.replace(reasp,'(','')
    repar2 = str.replace(repar1,')','')
    withoutupp = str.lower(repar2)
    splitng = withoutupp.split()
    revletters = list(reversed(splitng))
    return " ".join(revletters)