def inverte(frase):
    inv_frase = ' '.join(frase.split()[::-1])
    inv_frase = inv_frase.replace(',','')
    inv_frase = inv_frase.replace(':','')
    inv_frase = inv_frase.replace(';','')
    inv_frase = inv_frase.replace('-',' ')
    inv_frase = inv_frase.replace('!','')
    inv_frase = inv_frase.replace('?','')
    inv_frase = inv_frase.replace('.','')
    return inv_frase.lower()