def inverte(frase):
    a=frase.replace(',','')
    b=a.replace('-','')
    c=b.replace(':','')
    d=c.replace(';','')
    e=d.replace('.','')
    f=e.replace('!','')
    g=f.replace('?','')
    h=g.replace('...','')
    i=h.lower()
    j=i.split()
    return j[::-1].jpin('',)