def inverte(x):
    ''' função que dada uma frase retorna uma outra frase que contenha as mesmas palavras,
    da frase de entrada na ordem inversa'''
    x=x.split("?")
    x=" ".join(x)
    x=x.split("!")
    x=" ".join(x)
    x=x.split("-")
    x=" ".join(x)
    x=x.split("_")
    x=" ".join(x)
    x=x.split(",")
    x=" ".join(x)
    x=x.split(":")
    x=" ".join(x)
    x=x.split(";")
    x=" ".join(x)
    x=x.split(".")
    x=" ".join(x)
    x=x.split(" ")
    x= " ".join(x[::-1])
    x=x.strip()
    x=x.split("  ")
    x=" ".join(x)
    return x.lower()