def inverte(frase):
    x= str.lower(frase)
    x1= str.replace(x,',',' ')
    x2= str.replace(x1,'.',' ')
    x3=str.replace(x2,':',' ')
    x4= str.replace(x3,'-',' ')
    x5=str.replace(x4,';',' ')
    x6=str.replace(x5,'?',' ')
    x7=str.replace(x6,'!',' ')
    x8=str.split(x7)
    list.reverse(x8)
    return str.join(' ',x8)