def inverte(frase):
    frase1 = (frase[::-1])
    l1 = frase1.split("!")
    l2 = " ".join(l1)
    l3 = l2.split("?")
    l4 = " ".join(l3)
    l5 = l4.split("...")
    l6 = " ".join(l5)
    l7 = l6.split(".")
    l8 = " ".join(l7)
    l9 = l8.split(",")
    l10 = " ".join(l9)
    l11 = l10.split("-")
    l12 = " ".join(l11)
    return l12