def inverte(frase):
    frase=str.split(frase,",")
    frase1=str.join("",frase)
    frase2=str.split(frase1,".")
    frase3=str.join("",frase2)
    frase4=str.split(frase3,"!")
    frase5=str.join("",frase4)
    frase6=str.split(frase5,"?")
    frase7=str.join("",frase6)
    frase8=str.split(frase7,"-")
    frase9=str.join(" ",frase8)
    frase10=str.lower(frase9)
    frase11=str.split(frase10," ")
    frase12=str.split(frase11 "[]")
    return frase11[::-1]