def inverte(frase)
repor0=frase.replace('.',' ')
    repor1=repor0.replace('?',' ')
    repor2=repor1.replace('...',' ')
    repor3=repor2.replace('!',' ')
    repor4=repor3.replace(';',' ')
    repor5=repor4.replace('-',' ')
    repor6=repor5.replace(',',' ')
    repor7=repor6.replace(':',' ')
    lista=repor7.split('  ')
    lista0=' '.join(lista)
    lista1=lista0.split(' ')
    list.reverse(lista1)
    lista1=' '.join(lista1)
    return lista1[1:]