def inverte(texto):
    texto=texto.lower()
    texto=texto.replace("-","")
    texto=texto.replace(",","")
    texto=texto.replace(":","")
    texto=texto.replace(";","")
    texto=texto.replace(".","")
    texto=texto.replace("!","")
    texto=texto.replace("?","")
    texto=texto.replace("...","")
    texto=texto.split()
    texto=texto.reverse()
    texto=tupla(texto)
    texto=str.join("",texto)
    return texto