def inverte(frase):
    """Função que, data uma determinada frase, retorne uma outra com as mesmas palavras, mas na ordem inversa, além de estar sem letras maiúsculuas e pontuação; str=>str"""
	passo1 = (exclamacao = str.replace(frase,"!", " ")
    interrogacao = str.replace(exclamacao,"?", " ")
    virgula = str.replace(interrogacao,",", " ")
    reticencias = str.replace(virgula, "...", " ")
    ponto = str.replace(reticencias,".", " ")
    dois_pontos = str.replace(ponto,":", " ")
    ponto_virgula = str.replace(dois_pontos,";", " ")
    travessao = str.replace(ponto_virgula,"-", " ")
    (frase))
    passo2 = str.lower(passo1)
    lista = str.split(passo2)
    lista.reverse()
    return str.join(" ",lista)