def inverte(frase):
    frase=str.replace(frase,'?',' ')
    frase=str.replace(frase,'!',' ')
    frase=str.replace(frase,'.',' ')
    frase=str.replace(frase,',',' ')
    frase=str.replace(frase,':',' ')
    frase=str.replace(frase,'-',' ')
    frase=str.replace(frase,'A','a')
    frase=str.replace(frase,'B','b')
    frase=str.replace(frase,'C','c')
    frase=str.replace(frase,'D','d')
    frase=str.replace(frase,'E','e')
    frase=str.replace(frase,'F','f')
    frase=str.replace(frase,'G','g')
    frase=str.replace(frase,'H','h')
    frase=str.replace(frase,'I','i')
    frase=str.replace(frase,'J','j')
    frase=str.replace(frase,'K','k')
    frase=str.replace(frase,'L','l')
    frase=str.replace(frase,'M','m')
    frase=str.replace(frase,'N','n')
    frase=str.replace(frase,'O','o')
    frase=str.replace(frase,'P','p')
    frase=str.replace(frase,'Q','q')
    frase=str.replace(frase,'R','r')
    frase=str.replace(frase,'S','s')
    frase=str.replace(frase,'T','t')
    frase=str.replace(frase,'U','u')
    frase=str.replace(frase,'V','v')
    frase=str.replace(frase,'W','w')
    frase=str.replace(frase,'X','x')
    frase=str.replace(frase,'Y','y')
    frase=str.replace(frase,'Z','z')
    frase=frase[::-1]
    
    return frase