def inverte(frase):
    e0 = frase.lower()
    e1 = e0.replace('–', ' ')
    e2 = e1.replace(',', ' ')
    e3 = e2.replace(':', ' ')
    e4 = e3.replace(';', ' ')
    e5 = e4.replace('.', ' ')
    e6 = e5.replace('!', ' ')
    e7 = e6.replace('?', ' ')
    e8 = e7.replace('...', ' ')
    e9 = e8.replace('-', ' ')
    e10 = e9.split()
    e10.reverse()
    e11 = ' '.join(e10)
    return e11