def par(n):
    return n%2==0
def p(a,b,c,d):
    return (par(a),par(b),par(c),par(d))
def filtra_pares(a,b,c,d):
    if (p(a,b,c,d))==(True,True,True,True):
        return (a,b,c,d)
    if p(a,b,c,d)==(False,True,True,True):
        return (b,c,d)
    if p(a,b,c,d)==(True,False,True,True):
        return (a,c,d)
    if p(a,b,c,d)==(True,True,True,False):
        return (a,b,d)
    if p(a,b,c,d)==(False,False,True,True):
        return (c,d)
    if p(a,b,c,d)==(False,True,False,True):
        return (b,d)
    if p(a,b,c,d)==(False,True,True,False):
        return (b,c)
    if p(a,b,c,d)==(True,False,False,True):
        return (a,d)
    if p(a,b,c,d)==(True,False,True,False):
        return (a,d)
    if p(a,b,c,d)==(True,True,False,False):
        return (a,b)
    if p(a,b,c,d)==(True,False,False,False):
        return (a)
    if p(a,b,c,d)==(False,True,False,False):
        return (b)
    if p(a,b,c,d)==(False,False,True,False):
        return (c)
    if p(a,b,c,d)==(False,False,False,True):
        return (d)
    if p(a,b,c,d)==(False,False,False,False):
        return()