def filtra_pares(x,y,z,w):
    '''Filtra os elementos inteiros pares
    	int,int,int,int-> int'''
    if x%2=0:
        return x,y,z,w
    elif x/2!=int,y/2==int,z/2==int,w/2==int:
        return y,z,w
    elif x/2!=int,y/2!=int,z/2==int,w/2==int:
        return z,w
    elif x/2!=int,y/2!=int,z/2!=int,w/2==int:
        return w
    elif x/2==int,y/2!=int,z/2==int,w/2==int:
        return x,z,w
    elif x/2==int,y/2!=int,z/2!=int,w/2==int:
        return x,w
    elif x/2==int,y/2!=int,z/2!=int,w/2!=int:
        return x
    elif x/2==int,y/2==int,z/2!=int,w/2==int:
        return x,y,w
    elif x/2==int,y/2==int,z/2!=int,w/2!=int:
        return x,y
    elif x/2==int,y/2==int,z/2==int,w/2!=int:
        return x,y,z
    elif x/2==int,y/2!=int,z/2==int,w/2!=int:
        return x,z
    elif x/2!=int,y/2==int,z/2==int,w/2!=int:
        return y,z
    elif x/2!=int,y/2==int,z/2!=int,w/2==int:
        return y,w
    elif x/2!=int,y/2!=int,z/2==int,w/2!=int:
        return z
    elif x/2!=int,y/2==int,z/2!=int,w/2!=int:
        return y
    else:
        return ()