def filtra_pares(t):
    if t[0]%2!=0: 
        t[0]={} .format({},{},{},{})
    if t[1]%2!=0:
        t[1]={} .format({},{},{},{})
    if t[2]%2!=0:
        t[2]={} .format({},{},{},{})
    if t[3]%2!=0:
        t[3]={} .format({},{},{},{})
        return t[0],t[1],t[2],t[3]