def filtra_pares(x):
    def filtra_pares(x):
    if (x[0])%2==0:
        return x[0]
    elif (x[1])%2==0:
        return x[1]
    elif (x[2])%2==0:
        return x[2]
    elif (x[3])%2==0:
        return x[3]