def conta_frases(x):
    x=x.replace('  ',' ')
    x=x.replace('   ',' ')
    x=x.replace(',  ',' ')
    x=x.replace('; ',' ')
    x=x.replace(':   ',' ')
    x=x.replace('!  ',' * ')
    x=x.replace(' !',' * ')
    x=x.replace('!',' * ')
    x=x.replace('? ',' * ')
    x=x.replace('. ',' * ')
    x=x.replace('... ',' * ')
    x=x.split(' * ')
    return len(x)