def conta_frases(x):
    x.replace('  ',' ')
    x.replace('   ',' ')
    x.replace(',  ',' ')
    x.replace('; ',' ')
    x.replace(':   ',' ')
    x.replace('!  ',' * ')
    x.replace(' !',' * ')
    x.replace('!',' * ')
    x.replace('? ',' * ')
    x.replace('. ',' * ')
    x.replace('... ',' * ')
    x.split(' * ')
    return len(x)