def conta_frases(frase): 
    frase=frase.replace('.','=')
    f1=frase.replace('.','=')
    f1=f1.replace('.','=')
    frase=frase.replace('?','=')
    f2=frase.replace('?','=')
    f2=f2.replace('?','=')
    frase=frase.replace('!','=')
    f3=frase.replace('!','=')
    f3=f3.replace('!','=')
    frase=frase.replace('...','=')
    f4=frase.replace('...','=')
    f4=f4.replace('...','=')
    frase.split('=')
    return frase.split('=')