def conta_frases(frase):
   if frase.replace('...','.'):
    return len(frase.split('.'))
   elif frase.replace('?','.'):
    return len(frase.split('.'))
   elif frase.replace('!','.'):
    return len(frase.split('.'))
   elif frase.replace('.','.'):
    return len(frase.split('.'))