def filtraMultiplos(lista,n):
    if lista[0]%n==0:
        return [lista[0]]
    elif lista[1]%n==0:
        return [lista[1]]
    elif lista[2]%n==0:
        return [lista[2]]
    elif lista[3]%n==0:
        return [lista[3]]
    elif lista[4]%n==0:
        return [lista[4]]
    elif lista[5]%n==0:
        return [lista[5]]
    elif lista[6]%n==0:
        return [lista[6]]
        if lista[13]%n==0:
        return [lista[13]]
    elif lista[7]%n==0:
        return [lista[7]]
    elif lista[8]%n==0:
        return [lista[8]]
    elif lista[9]%n==0:
        return [lista[9]]
    elif lista[10]%n==0:
        return [lista[10]]
    elif lista[11]%n==0:
        return [lista[11]]
    elif lista[12]%n==0:
        return [lista[12]]
    else:
        return []