def posLetra(t, l, n):
    def posLetra(t, l, n):
    correncias = []                  #Lista em que serão salvas as posições de cada ocorrencia de l
    for c in enumerate(t):           #Para cada tupa c na enumeração de t...
        if c[1] == l:                ##...se o caractere enumerado for igual a l...
            correncias.append(c[0])  ##...adiciona sua posição na lista de correncias.
    if n >= len(correncias):         #Se a ocorrência a se pesquisada for maior que a quantidade de ocorrência encontradas...
        return -1                    #...retorna -1.