def hashtag(s):
    '''retorna a funcao que recebe um hashtag no inicio, no meio e no final da string, sendo s a string indicada'''
    string= str(s[0:1])
    string0= str(s[0:3])
    string1= str(s[0:5])
    string2= str(s[0:7])
    string3= str(s[0:9])
    string4= str(s[0:11])
    string5= str(s[0:13])
    string6= str(s[0:15])
    funcao= '#'+'#'+s[:1]+s[1:]+'#'
    funcao0= '#'+s[:1]+'#'+s[1:]+'#'
    funcao1= '#'+s[:2]+'#'+s[2:]+'#'
    funcao2= '#'+s[:3]+'#'+s[3:]+'#'
    funcao3= '#'+s[:4]+'#'+s[4:]+'#'
    funcao4= '#'+s[:5]+'#'+s[5:]+'#'
    funcao5= '#'+s[:6]+'#'+s[6:]+'#'
    funcao6= '#'+s[:7]+'#'+s[7:]+'#'
    if s<=string1 and s!=string and s!=string0:
        return funcao1
    elif s<=string:
        return funcao
    elif s<=string0:
        return funcao0
    elif s<=string2:
        return funcao2
    elif s<=string3:
        return funcao3
    elif s<=string4:
        return funcao4
    elif s<=string5:
        return funcao5
    elif s<=string6:
        return funcao6