def colchao(medidas,H,L):
     if medidas[2]<H:
            return True
        if medidas[2]<L:
            return True
        if medidas[3]<H:
            return True
        if medidas[3]<L:
            return True