def retira_pontuacao(frase):
    str.replace(texto,'-',' ')
    str.replace(texto,',',' ')
    str.replace(texto,':',' ')
    str.replace(texto,';',' ')
    str.replace(texto,'?',' ')
    str.replace(texto,'!',' ')
    str.replace(texto,'...',' ')
    return frase