def retira_pontuacao(frase):
    x=str.replace(frase,'.',' ')
    y=str.replace(frase,',',' ')
    z=str.replace(frase,':',' ')
    w=str.replace(frase,';',' ')
    t=str.replace(frase,'!',' ')
    u=str.replace(frase,'?',' ')
    v=str.replace(frase,'-',' ')
    a=str.join(' ',str.split(frase,'.'))
    b=str.join(' ',str.split(a,','))
    return a+b