def retira_pontuacao(s):
    a=str.replace(s,"-"," ")
    a=str.replace(s,":"," ")
    a=str.replace(s,";"," ")
    a=str.replace(s,","," ")
    a=str.replace(s,"."," ")
    a=str.replace(s,"!"," ")
    a=str.replace(s,"?"," ")
    return a