def retira_pontuacao(m):
    str.replace(m,'-',' ')
    str.replace(m,'.',' ')
    str.replace(m,':',' ')
    str.replace(m,';',' ')
    str.replace(m,'!',' ')
    str.replace(m,'?',' ')
    str.replace(m,',',' ')
    str.replace(m,'/',' ')
    return m