def retira_pontuacao(frase):
  C=str.split(frase,'-')
  texto1=str.join(' ',k)
  texto2=str.split(texto1,'...')
  texto3=str.join(' ',texto2)
  texto4=str.split(texto3,',')
  texto5=str.join(' ',texto4)
  texto6=str.split(texto5,'.')
  texto7=str.join(' ',texto6)
  texto8=str.split(texto7,':')
  texto9=str.join(' ',texto8)
  texto10=str.split(texto9,'!')
  texto11=str.join(' ',texto10)
  texto12=str.split(texto11,'?')
  texto13=str.join(' ',texto12)
  texto14=str.split(texto13,';')
  textoF=str.join(' ',texto14)
  return textoF