def retira(frase):
    frase=frase.replace(',',' ')
    frase=frase.replace('.',' ')
    frase=frase.replace('!',' ')
    frase=frase.replace('?',' ')
    frase=frase.replace('-',' ')
    frase=frase.replace(';',' ')
    frase=frase.replace(':',' ')
    return frase