def retira_pontuacao(a):
    a=str.replace(a,","," ")
    a=str.replace(a,"-"," ")
    a=str.replace(a,"!"," ")
    a=str.replace(a,":"," ")
    a=str.replace(a,";"," ")
    a=str.replace(a,"."," ")
    a=str.replace(a,"?"," ")
    return a