def retira_pontuacao(rp):
    rp=str.replace(rp,"-"," ")
    rp=str.replace(rp,"!"," ")
    rp=str.replace(rp,";"," ")
    rp=str.replace(rp,":"," ")
    rp=str.replace(rp,","," ")
    rp=str.replace(rp,"?"," ")
    rp=str.replace(rp,"."," ")
    return rp