def retira_pontuacao(frase):
    str.replace(frase,"!",' ')
    str.replace(frase,",",' ')
    str.replace(frase,";",' ')
    str.replace(frase,"!",' ')
    str.replace(frase,".",' ')
    str.replace(frase,"?",' ')
    str.replace(frase,".",' ',-1)
    return frase