def retira_pontuacao(string):
    a=string.replace("-"," ")
    b=a.replace(","," ")
    c=b.replace(":"," ")
    d=c.replace(";"," ")
    e=d.replace("!"," ")
    f=e.replace("?"," ")
    g=f.replace("."," ")
    return g