def retira_pontuacao(rp):
    str.replace(rp,"-"," ")
    str.replace(rp,"!"," ")
    str.replace(rp,";"," ")
    str.replace(rp,":"," ")
    str.replace(rp,","," ")
    str.replace(rp,"?"," ")
    str.replace(rp,"."," ")
    return rp