def retira_pontuacao(frase):
    trav=str.replace(frase,"-"," ")
    vig=str.replace(trav,","," ")
    doispon=str.replace(vig,":"," ")
    ponvig=str.replace(doispon,";"," ")
    pon=str.replace(ponvig,"."," ")
    excla=str.replace(pon,"!"," ")
    inter=str.replace(excla,"?"," ")
    return inter