def retira_pontuacao(frase):
    b=frase.replace('!',' ')
    b=b.replace('.',' ')
    b=b.replace('?',' ')
    b=b.replace(';',' ')
    b=b.replace(':',' ')
    b=b.replace(',',' ')
    b=b.replace('-',' ')
    b=b.replace('...',' ')