def retira_pontuacao(frase):
    texto.replace('-',' ')
    texto.replace(',',' ')
    texto.replace(':',' ')
    texto.replace(';',' ')
    texto.replace('.',' ')
    texto.replace('...',' ')
    texto.replace('!',' ')
    texto.replace('?',' ')
    return texto