def retira_pontuaçao(frase):
    frase=frase.split('-')
    frase=' '.join(frase)
    frase=frase.split(',')
    frase=' '.join(frase)
    frase=frase.split('.')
    frase=' '.join(frase)
    frase=frase.split('...')
    frase=' '.join(frase)
    frase=frase.split('?')
    frase=' '.join(frase)
    frase=frase.split('!')
    frase=' '.join(frase)
    frase=frase.split(':')
    frase=' '.join(frase)
    frase=frase.split(';')
    frase=' '.join(frase)
    return frase