def retira_pontuacao(frase)
    x=str.replace(frase,'.',' ')
    y=str.replace(x,',',' ')
    z=str.replace(y,':',' ')
    w=str.replace(z,';',' ')
    t=str.replace(w,'!',' ')
    u=str.replace(t,'?',' ')
    v=str.replace(u,'-',' ')
   return v