def troca(x):
    y = str.replace(x, 'q','Q')
    w = str.replace(y, 'w','W')
    e = str.replace(w, 'r','R')
    r = str.replace(e, 't','T')
    t = str.replace(r, 'y','Y')
    m = str.replace(t, 'p','P')
    u = str.replace(m, 's','S')
    i = str.replace(u, 'd','D')
    o = str.replace(i, 'f','F')
    p = str.replace(o, 'g','G')
    a = str.replace(p, 'h','H')
    s = str.replace(a, 'j','J')
    d = str.replace(s, 'k','K')
    f = str.replace(d, 'l','L')
    g = str.replace(f, 'ç','Ç')
    h = str.replace(g, 'z','Z')
    ç = str.replace(h, 'x','X')
    j = str.replace(ç, 'c','C')
    k = str.replace(j, 'v','V')
    n = str.replace(k, 'b','B')
    b = str.replace(n, 'n','N')
    v = str.replace(b, 'm','M')
    return v