def uppCons(texto):
    texto=str.replace(texto,'b','B')
    texto=str.replace(texto,'c','C')
    texto=str.replace(texto,'d','D')
    texto=str.replace(texto,'f','F')
    texto=str.replace(texto,'g','G')
    texto=str.replace(texto,'h','H')
    texto=str.replace(texto,'j','J')
    texto=str.replace(texto,'k','K')
    texto=str.replace(texto,'l','L')
    texto=str.replace(texto,'m','M')
    texto=str.replace(texto,'n','N')
    texto=str.replace(texto,'p','P')
    texto=str.replace(texto,'q','Q')
    texto=str.replace(texto,'r','R')
    texto=str.replace(texto,'s','S')
    texto=str.replace(texto,'t','T')
    texto=str.replace(texto,'v','V')
    texto=str.replace(texto,'w','W')
    texto=str.replace(texto,'x','X')
    texto=str.replace(texto,'y','Y')
    texto=str.replace(texto,'z','Z')
    return texto